[package]
name = "pack-format"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ciborium = "0.2.2"
glob = "0.3.3"
itertools = "0.14.0"
json5 = "0.4.1"
merge = "0.2.0"
serde = "1.0.219"
walkdir = "2.5.0"
