[package]
name = "lewdware"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared/" }
anyhow = "1.0.99"
egui = { version = "0.32.1", features = ["serde"] }
egui-wgpu = "0.32.1"
egui-winit = "0.32.1"
ffmpeg-next = "8.0.0"
image = { version = "0.25.6", default-features = false, features = ["avif-native"] }
wgpu = { version = "25.0.2", features = ["static-dxc"] }
notify-rust = "4.11.7"
pixels = "0.15.0"
rand = "0.9.2"
rdev = "0.5.3"
rodio = "0.21.1"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
softbuffer = "0.4.6"
tempfile = "3.21.0"
webbrowser = "1.0.5"
winit = "0.30.12"
ab_glyph = "0.2.31"
wallpaper = "3.2.0"
dirs = "6.0.0"
rand_distr = "0.5.1"
walkdir = "2.5.0"
tokio = { version = "1.48.0", features = ["full"] }
pollster = "0.4.0"

[features]
static-ffmpeg = ["ffmpeg-next/static"]
build-ffmpeg = ["ffmpeg-next/build"]
